stages:
  - dump
  - analyze
  - deploy

dump-job:
  stage: dump
  script:
    - echo "Running on a $(uname -a) from $(pwd) on machine $(hostname)"
    - ls -l
    - echo "Started at $(date)"
    - echo "Downloading database dump"
    - backend/dump.py --start 2023-01-01 --end 2023-03-30 --overwrite
    - ls -l
    - echo "Finished at $(date)"

analyze-job:
  stage: analyze
  script:
    - echo "Running on a $(uname -a) from $(pwd) on machine $(hostname)"
    - ls -l
    - echo "Started at $(date)"
    - echo "Analyzing database dump"
    - backend/create_json.py
    - ls -l
    - echo "Finished at $(date)"

deploy-job:
  stage: deploy
  script:
    - echo "Running on a $(uname -a) from $(pwd) on machine $(hostname)"
    - ls -l
    - echo "Started at $(date)"
    - echo "Finished at $(date)"